// Generated by CoffeeScript 1.6.1

exports.config = {
  server_port: 9000,
  sockets_port: 9001,
  leaveat: 5,
  countdown: 120,
  resetAllDelay: 60,
  log_level: 1,
  transports: ['websocket', 'htmlfile', 'xhr-polling', 'jsonp-polling'],
  allowedDomains: "*"
};
